Project 5 - Design Teardown
praz99/designTeardown pull request #1
Opened 2020-04-01 15:48 UTC by expjazz

The project involves putting elements into the right position and focusing on mapping the UX and UI of the original Smashing Magazine Website.

We used the grid system, also flexbox for positioning. For the background, we used scales of grey, with as darker the color more important is the item. 

We also imported a font from the Google Fonts in which we think that it suited the project better.

2020-04-01 23:03 UTC, thsvr commented
### **STATUS: CHANGES REQUIRED** :+1: :+1: 

Hi @expjazz and @praz99 :smile_cat: :smile_cat: 


Your page looks beautiful and you guys are doing a great job :fireworks:  So you guys are almost there! **Can you please read carefully the required changes below? They are necessary to be implemented on the project** :+1: 

:v: In this project, article tag has to be used for each article. [Here](https://www.w3schools.com/tags/tag_article.asp) you guys can read and understand more about it. Can you please fix it?

:v: [Here](https://www.w3schools.com/tags/tag_footer.asp) you guys can read about footer tag and where it is important to be implemented. Can you please consider it?

:v: Can you please update the live version on readme? 

**SUGGESTION FOR THE NEXT PROJECTS:**

:v: You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''greyscale-page'', for example. It will be more descriptive. :+1: :+1: 

If you have any questions, don't hesitate to contact me through slack[ @thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next review** :computer: :computer: 

_Project reviewed by Thaís Vieira (TSE)_

2020-04-02 09:06 UTC, mikenath223 commented
**Pull request currently under review by Michgolden Ukeje (TSE).**
Kindly exercise patience 🐱

2020-04-02 09:40 UTC, mikenath223 requested changes
### Hi Team👋

You've worked quite hard on this @expjazz and @praz99 👨‍💻👏

However, there are a few changes that need to be made before proceeding.
**Hang in there, we've got you.💪**



- [ ] Required - There are differences between the original webpage and yours, kindly ensure you clone the visual hierarchy of the page, with the way the templates look. Consider this:

**THIS IS THE WAY THE ORIGINAL LOOKS ON THE SECTION ALMOST TO THE MIDDLE OF THE PAGE**👇

![ice_screenshot_20200402-101239](https://user-images.githubusercontent.com/33323077/78233061-1a80fc80-74cd-11ea-839c-f7c6a10448e6.png)

**THIS IS THE WAY THE NEXT SECTION THAT FOLLOWS IT LOOKS LIKE**👇
![ice_screenshot_20200402-101250](https://user-images.githubusercontent.com/33323077/78233206-4bf9c800-74cd-11ea-83bd-0df05008ee01.png)

**FIX THIS ISSUES IN YOURS, CLONING THE VISUAL LOOK OF IT THE TEXT CONTENT DOES'T MATTER.**

- [ ] Required - The newsletter section just before the footer completely fills the full-width of the page.and also the section directly above it contains four(4) templates positioned side-by-side, ensure you have the same on yours too.

**THIS IS THE NEWSLETTER SECTION JUST BEFORE THE FOOTER👇**
![ice_screenshot_20200402-094526](https://user-images.githubusercontent.com/33323077/78233636-f245cd80-74cd-11ea-944d-7d15bf041c38.png)

**THIS IS THE FOUR(4) TEMPLATES SECTIONS THAT COME BEFORE IT**👇
![ice_screenshot_20200402-103904](https://user-images.githubusercontent.com/33323077/78233824-389b2c80-74ce-11ea-8f11-7d85ecc0b0c7.png)

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAVE A SMASHING CODING DAY! 👨‍💻👋**

2020-04-02 13:48 UTC, sumancrest0001 commented on style.css
> +}
We do not have to use a grid. Just make keep it simple and align all the items at the center of the footer box.

2020-04-02 13:48 UTC, sumancrest0001 commented
### Status: Required a change

Great job TEAM :clap: :clap: 
Everything looks great but one small change is required to get :+1: :+1:  for this project.

It is quite simple but we have to tick all the requirements. Please make the change and submit for another review.
![Screenshot from 2020-04-02 19-27-33](https://user-images.githubusercontent.com/37747619/78256355-22b25980-7518-11ea-883a-9a33c1ac4f1f.png)

**It should be like this :point_down:** 
![Screenshot from 2020-04-02 19-27-17](https://user-images.githubusercontent.com/37747619/78256402-31007580-7518-11ea-8878-21ea97b9ca69.png)

2020-04-02 14:06 UTC, expjazz commented
As required by the last review, we made the necessary adjustments to the footer.

2020-04-02 15:00 UTC, men32z approved these changes
## Good job making the changes, you can merge.

![BlgS1sdIUAEybkW](https://user-images.githubusercontent.com/9115996/78264312-3df17a80-74c0-11ea-88a3-75d93f3a2d87.jpg)

### Status Approved

2020-04-02 15:04 UTC, merged